Consolidate build.sh's/build-cli.sh's/python wrappers, improve build.
Improvements:
- fix gopath handling, fix the go build warning
- shrink CLIs where possible (darwin dislikes upx)
- some build log prittification

diff --git a/new-service b/new-service
--- a/new-service
+++ b/new-service
@@ -1,33 +1,30 @@
-#!/bin/sh
+#!/bin/bash
 
-if [ -z $1 ]; then
-	echo "You must provide the name of the project as the first argument"
-	echo "Usage: ./new-service <dir-path>/<project-name>"
-	echo "Example: ./new-service examples/kafka"
-	exit 1
+if [ $# -lt 1 ]; then
+    echo "You must provide the name of the project as the first argument"
+    echo "Usage: ./new-service.sh <dir-path>/<project-name>"
+    echo "Example: ./new-service.sh frameworks/kafka"
+    exit 1
 elif [ -d $1 ]; then
-	echo "A project with the given name already exists. Choose a different name"
-	exit 1
+    echo "A project with the given name already exists. Choose a different name"
+    exit 1
 fi
 
 PROJECT_NAME=$(basename $1)
 PROJECT_PATH=$(dirname $1)
 
-if [ ! -d $PROJECT_PATH ]; then
-	mkdir -p $PROJECT_PATH
-fi
+mkdir -p $PROJECT_PATH
 
 cp -R frameworks/helloworld $1
 rm -rf $1/build
-rm -rf $1/cli/python/build/lib/bin_wrapper/binaries
-rm -rf $1/cli/dcos-hello-world/dcos-*
-rm -rf $1/cli/python/dist/bin_wrapper-0.0.1-py2.py3-none-any.whl
+rm -rf $1/cli/dcos-*/*.whl
+rm -rf $1/cli/dcos-*/dcos-*
 mv $1/cli/dcos-hello-world $1/cli/dcos-$PROJECT_NAME
 mv $1/src/test/java/com/mesosphere/sdk/helloworld/ $1/src/test/java/com/mesosphere/sdk/$PROJECT_NAME/
 
 if [ ! -d $1 ]; then
-	echo "Failed to create new project"
-	exit 1
+    echo "Failed to create new project"
+    exit 1
 fi
 
 UPPER_CASE_PROJECT_NAME=$(echo $PROJECT_NAME | awk '{print toupper($0)}')
@@ -38,17 +35,17 @@ sed -i.bak -e '23,26 d' $1/universe/marathon.json.mustache
 find $1 -type f -name *.bak -exec rm {} \;
 
 if [ $? -eq 0 ]; then
-	echo "" >> settings.gradle
-	if grep -q $PROJECT_NAME settings.gradle 
-	then
-	  echo "include '$1'" >> settings.gradle
-	  echo "project(\":$1\").name = \"$1\"" >> settings.gradle
-	else
-	  echo "include '$1'" >> settings.gradle
-	  echo "project(\":$1\").name = \"$PROJECT_NAME\"" >> settings.gradle
-	fi
-	echo "New project created successfully"
+    echo "" >> settings.gradle
+    if grep -q $PROJECT_NAME settings.gradle
+    then
+	echo "include '$1'" >> settings.gradle
+	echo "project(\":$1\").name = \"$1\"" >> settings.gradle
+    else
+	echo "include '$1'" >> settings.gradle
+	echo "project(\":$1\").name = \"$PROJECT_NAME\"" >> settings.gradle
+    fi
+    echo "New project created successfully"
 else
-	echo "Failed to create new project"
-	exit 1
+    echo "Failed to create new project"
+    exit 1
 fi
