Add check-settings-s3 plan.

diff --git a/frameworks/cassandra/src/main/dist/svc.yml b/frameworks/cassandra/src/main/dist/svc.yml
--- a/frameworks/cassandra/src/main/dist/svc.yml
+++ b/frameworks/cassandra/src/main/dist/svc.yml
@@ -135,12 +135,16 @@ pods:
         cmd: |
               export PATH=$MESOS_SANDBOX/python-dist/bin:$PATH
               export LD_LIBRARY_PATH=$MESOS_SANDBOX/openssl-dist:$LD_LIBRARY_PATH
-              echo "Checking access to s3://${S3_BUCKET_NAME}"
-              aws s3 ls s3://${S3_BUCKET_NAME} > /dev/null 2>&1
-              if [ $? -ne 0 ]; then
-                echo "Checking s3 connection failed. Please check your settings and try again"
-                exit 1
-              fi
+              while true; do
+                echo "Checking access to s3://${S3_BUCKET_NAME}"
+                aws s3 ls s3://${S3_BUCKET_NAME} > /dev/null 2>&1
+                if [ $? -eq 0 ]; then
+                  echo "Connection to s3 successful"
+                  exit 0
+                fi
+                echo "Connection to s3 failed. Please check your settings and try again"
+                sleep 60
+              done
         resource-set: sidecar-resources
       upload-s3:
         goal: ONCE
@@ -306,10 +310,18 @@ plans:
         pod: node
         steps:
           - default: [[cleanup]]
+  check-settings-s3:
+    strategy: serial
+    phases:
+      check-settings:
+        strategy: {{BACKUP_RESTORE_STRATEGY}}
+        pod: node
+        steps:
+          - default: [[check-settings-s3]]
   backup-s3:
     strategy: serial
     phases:
-      check-settings-s3:
+      check-settings:
         strategy: {{BACKUP_RESTORE_STRATEGY}}
         pod: node
         steps:
@@ -337,7 +349,7 @@ plans:
   restore-s3:
     strategy: serial
     phases:
-      check-settings-s3:
+      check-settings:
         strategy: {{BACKUP_RESTORE_STRATEGY}}
         pod: node
         steps:
